/**
 ComBroker events
 **/

BB.EVENTS.SCENE_BLOCK_LIST_UPDATED = 'SCENE_BLOCK_LIST_UPDATED';
BB.EVENTS.SCENE_ITEM_SELECTED = 'SCENE_ITEM_SELECTED';
BB.EVENTS.LOAD_SCENE = 'LOAD_SCENE';
BB.EVENTS.SCENE_ZOOM_IN = 'SCENE_ZOOM_IN';
BB.EVENTS.SCENE_ZOOM_OUT = 'SCENE_ZOOM_OUT';
BB.EVENTS.SCENE_ZOOM_RESET = 'SCENE_ZOOM_RESET';
BB.EVENTS.SCENE_PUSH_TOP = 'SCENE_PUSH_TOP';
BB.EVENTS.SCENE_PUSH_BOTTOM = 'SCENE_PUSH_BOTTOM';
BB.EVENTS.SCENE_EDITOR_REMOVE = 'SCENE_EDITOR_REMOVE';
BB.EVENTS.SCENE_ITEM_REMOVE = 'SCENE_ITEM_REMOVE';
BB.EVENTS.NEW_SCENE_ADD = 'NEW_SCENE_ADD';
BB.EVENTS.NEW_SCENE_ADDED = 'NEW_SCENE_ADDED';
BB.EVENTS.SCENE_UNDO = 'SCENE_UNDO';
BB.EVENTS.SCENE_REDO = 'SCENE_REDO';
BB.EVENTS.REMOVING_SCENE = 'REMOVING_SCENE';
BB.EVENTS.REMOVED_SCENE = 'REMOVED_SCENE';
BB.EVENTS.REMOVING_RESOURCE = 'REMOVING_RESOURCE';
BB.EVENTS.REMOVED_RESOURCE = 'REMOVED_RESOURCE';
BB.EVENTS.ADDED_RESOURCE = 'ADDED_RESOURCE';
