// Providers
Services.APP_ENTRY_FADER_VIEW = 'APP_ENTRY_FADER_VIEW';
Services.APP_CONTENT_FADER_VIEW = 'APP_CONTENT_FADER_VIEW';
Services.LAYOUT_MANAGER = 'LAYOUT_MANAGER';
Services.PROPERTIES_PANEL = 'PROPERTIES_PANEL';
Services.POP_MODAL_VIEW = 'POP_MODAL_VIEW';
Services.RESOLUTION_SELECTOR = 'RESOLUTION_SELECTOR';
Services.ORIENTATION_SELECTOR = 'ORIENTATION_SELECTOR';

// Subscribables
AppEvents.APP_SIZED = 'APP_SIZED';

// Constants
Consts.HORIZONTAL = 'HORIZONTAL';
Consts.VERTICAL = 'VERTICAL';
Consts.ORIENTATION = 'ORIENTATION';
Consts.RESOLUTION = 'RESOLUTION';


function AppEvents() {
};
function Services() {
};
function Consts() {
};

